import asyncio,sys
from playwright.async_api import async_playwright
BASE=sys.argv[1] if len(sys.argv)>1 else 'file:///workspace/wilson-water-pirates/index.html'
OUT='/workspace/wilson-water-pirates/';ok=True
def chk(n,c,i=''):
    global ok;ok&=bool(c);print(('PASS ' if c else 'FAIL ')+n,i)
async def run(p,b,name,dev,shots):
    errs=[];ctx=await b.new_context(**dev);m=await ctx.new_page()
    m.on('pageerror',lambda e:errs.append(str(e)));m.on('console',lambda x:errs.append(x.text) if x.type=='error' else None)
    await m.goto(BASE);await m.wait_for_timeout(500);chk(f'[{name}] no debug hook in public build',await m.evaluate('typeof window.__W')=='undefined')
    await m.goto(BASE+('&' if '?' in BASE else '?')+'debug=1');await m.wait_for_timeout(800)
    vp=await m.evaluate('[innerWidth,innerHeight]')
    await m.touchscreen.tap(vp[0]*0.1,vp[1]*0.35);await m.wait_for_timeout(1200)
    a=await m.evaluate('({u:__W.audio.unlocked,r:__W.audio.running,c:__W.audio.clipCount,s:__W.state})')
    chk(f'[{name}] first tap unlocks audio',a['u'] and a['r'] and a['s']=='title',str(a));chk(f'[{name}] 20 voice clips decoded',a['c']==20,str(a['c']))
    if shots is not None: await m.screenshot(path=OUT+f'screenshot-title{shots}.png')
    await m.evaluate('__W.start()');await m.wait_for_timeout(3500)
    chk(f'[{name}] playing',await m.evaluate('__W.state')=='play')
    x0=await m.evaluate('__W.canoe.x')
    c=await m.evaluate('__W.toClient(__W.canoe.x,__W.CY()+60)')
    await m.touchscreen.tap(c['x']-90*vp[0]/400,c['y']);await m.wait_for_timeout(800)
    x1=await m.evaluate('__W.canoe.x');chk(f'[{name}] tap below steers',x1<x0-30,f'{x0:.0f}->{x1:.0f}')
    await m.evaluate('__W.clear();__W.spawn("duck",200,__W.CY()-220);__W.spawn("paddler",120,__W.CY()-300)')
    t=await m.evaluate('__W.toClient(200,__W.CY()-220)');await m.touchscreen.tap(t['x'],t['y']);await m.wait_for_timeout(700)
    s=await m.evaluate('({s:__W.splashes,sc:__W.score,v:__W.audio.stats.voice})');chk(f'[{name}] Alex soaker splashes duck',s['s']>=1,str(s))
    await m.evaluate('__W.switchShooter()');t=await m.evaluate('__W.toClient(120,__W.CY()-300)');await m.touchscreen.tap(t['x'],t['y']);await m.wait_for_timeout(900)
    chk(f'[{name}] Zoe balloon splashes paddler',await m.evaluate('__W.splashes')>=2)
    await m.evaluate('__W.gold("smore",__W.canoe.x,__W.CY()-60);__W.gold("coin",__W.canoe.x,__W.CY()-120)');await m.wait_for_timeout(1500)
    chk(f'[{name}] treasure collected',await m.evaluate('__W.treasure')>=1)
    for k,x,y in [('duck',90,-250),('frog',300,-200),('tuber',230,-330),('raft',150,-420),('bear',40,-150),('fish',260,-120)]:
        await m.evaluate(f'__W.spawn("{k}",{x},__W.CY()+({y}))')
    await m.evaluate('__W.gold("coin",200,__W.CY()-160);__W.gold("ducky",230,__W.CY()-60);__W.rock(320,__W.CY()-280,"log")')
    await m.wait_for_timeout(600)
    if shots is not None:
        t=await m.evaluate('__W.toClient(300,__W.CY()-200)');await m.touchscreen.tap(t['x'],t['y']);await m.wait_for_timeout(250)
        await m.screenshot(path=OUT+f'screenshot-gameplay{shots}.png')
    await m.evaluate('__W.dadGo()');await m.wait_for_timeout(2300)
    chk(f'[{name}] Dad Saves the Day sequence',await m.evaluate('__W.state')=='dad')
    if shots is not None: await m.screenshot(path=OUT+f'screenshot-dad-saves{shots}.png')
    await m.wait_for_timeout(4000)
    if shots is not None: await m.screenshot(path=OUT+f'screenshot-splash-cam{shots}.png')
    await m.wait_for_timeout(2300)
    if shots is not None: await m.screenshot(path=OUT+f'screenshot-stamp{shots}.png')
    await m.wait_for_timeout(3500)
    st=await m.evaluate('({s:__W.state,h:__W.hearts,d:__W.dadFalls,last:__W.audio.stats.last})');chk(f'[{name}] back to play, hearts restored',st['s']=='play' and st['h']==3,str(st))
    await m.evaluate('__W.end()');await m.wait_for_timeout(2600)
    chk(f'[{name}] end screen',await m.evaluate('__W.state')=='end')
    if shots is not None: await m.screenshot(path=OUT+f'screenshot-end{shots}.png')
    vs=await m.evaluate('__W.audio.stats');chk(f'[{name}] voice lines played',vs['voice']>=3,str(vs))
    chk(f'[{name}] no JS errors',not errs,str(errs[:3]))
    await ctx.close()
async def main():
    async with async_playwright() as p:
        b=await p.chromium.launch(executable_path='/usr/bin/google-chrome',args=['--autoplay-policy=no-user-gesture-required'])
        await run(p,b,'iPhone 13',p.devices['iPhone 13'],'')
        await run(p,b,'iPad',p.devices['iPad (gen 7)'],'-ipad')
        await b.close()
    print('ALL OK' if ok else 'SOME FAILED')
asyncio.run(main())
